# Generated by Django 3.1.1 on 2020-10-23 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='test',
            name='answer',
        ),
        migrations.AddField(
            model_name='question',
            name='answer',
            field=models.IntegerField(choices=[(1, '<django.db.models.fields.TextField>'), (2, '<django.db.models.fields.TextField>'), (3, '<django.db.models.fields.TextField>')], null=True),
        ),
    ]
