# Generated by Django 3.1.1 on 2020-10-22 15:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('license_plate', models.CharField(max_length=10)),
                ('millage', models.FloatField(default=0)),
                ('fuel_consumption', models.FloatField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Dimensions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('height', models.FloatField(default=0)),
                ('length', models.FloatField(default=0)),
                ('width', models.FloatField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Driver',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('car', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='car_park_app.car')),
                ('driver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='driver', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Fuel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fuel_type', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Manager',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('manager', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Repair',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('problem', models.TextField(verbose_name='Malfunction in ...')),
                ('date_in', models.DateField(verbose_name='Repair date')),
                ('date_out', models.DateField(verbose_name='Repair completion date')),
                ('cost', models.FloatField(default=0)),
                ('driver', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='repair', to='car_park_app.driver')),
            ],
        ),
        migrations.CreateModel(
            name='Refuel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('volume', models.FloatField(default=0)),
                ('cost', models.FloatField(default=0)),
                ('date', models.DateField(default=django.utils.timezone.now, verbose_name='Date of refuel')),
                ('car', models.ManyToManyField(to='car_park_app.Car')),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weight', models.FloatField(default=0)),
                ('place_from', models.TextField(verbose_name='Place from')),
                ('place_to', models.TextField(verbose_name='Place to')),
                ('milleage', models.FloatField(default=0, verbose_name='Total distance')),
                ('time', models.DateField(verbose_name='Order completion date')),
                ('car', models.ManyToManyField(to='car_park_app.Car')),
                ('dimensions', models.ManyToManyField(to='car_park_app.Dimensions')),
                ('driver', models.ManyToManyField(to='car_park_app.Driver')),
                ('manager', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='car_park_app.manager')),
            ],
        ),
        migrations.CreateModel(
            name='CarType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('body_type', models.CharField(choices=[('C', 'Passenger car'), ('B', 'Bus'), ('T', 'Truck')], default='C', max_length=1)),
                ('name', models.CharField(max_length=30)),
                ('carrying_capacity', models.IntegerField(default=0)),
                ('dimensions', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='car_park_app.dimensions')),
            ],
        ),
        migrations.AddField(
            model_name='car',
            name='car_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='car_park_app.cartype'),
        ),
        migrations.AddField(
            model_name='car',
            name='fuel_type',
            field=models.ManyToManyField(to='car_park_app.Fuel'),
        ),
    ]
